version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: gfd-sse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - gfd-sse-network

  dummy-off2on:
    build:
      context: ../dummy-off2on
      dockerfile: Dockerfile
    container_name: dummy-off2on
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - gfd-sse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  dummy-off2on-redis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dummy-off2on-redis
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
      dummy-off2on:
        condition: service_healthy
    networks:
      - gfd-sse-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
    driver: local

networks:
  gfd-sse-network:
    driver: bridge

