package com.gfd_sse.dummyoff2onredisreplica.event;


public enum EventType {
  PRODUCT_VIEWED,
  CART_ITEM_ADDED,
  CART_ITEM_REMOVED,
  CART_UPDATED,
  CART_DELETED,
  VOUCHER_APPLIED,
  VOUCHER_UNAPPLIED,
  DISCOUNT_APPLIED,
  DISCOUNT_REMOVED,
  CHECKOUT_INITIATED,
  CHECKOUT_CANCELLED,
  CHECKOUT_COMPLETED,
  CHECKOUT_FAILED,
  CONNECTION_ESTABLISHED,
  HEARTBEAT
}

