package com.gfd_sse.dummyoff2onredis.event;

public enum EventType {
    PRODUCT_VIEWED,
    CART_ITEM_ADDED,
    CART_ITEM_REMOVED,
    CART_UPDATED,
    CHECKOUT_INITIATED,
    CHECKOUT_COMPLETED,
    CHECKOUT_FAILED,
    CONNECTION_ESTABLISHED,
    HEARTBEAT
}
