version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: off2on-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - off2on-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
    driver: local

networks:
  off2on-network:
    driver: bridge

